[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
if = "!has('nvim')"
hook_post_update = '''

  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd

'''



[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested try | colorscheme hybrid | catch | endtry
'''

# sudo.vim
# usage:
# vim sudo:hoge		sudo権限でhogeを編集
# :w sudo:%			sudo権限でwrite
# :w sudo:piyo		sudo権限でpiyoに保存
# :e sudo:%			sudo権限で開き直す
[[plugins]]
repo = 'vim-scripts/sudo.vim'



# プロジェクトのrootディレクトリを探す子
[[plugins]]
repo = 'airblade/vim-rooter'

# tags自動更新
[[plugins]]
repo = 'szw/vim-tags'






