
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
"  source ~/.vim/rc/plugins/deoplete.rc.vim
call g:myconf.source_plugin_conf('deoplete.nvim')
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_i = 1
on_ft = 'go'
#hook_source = '''
#let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
#let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
#'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/usr/lib64/llvm/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'
'''
