
" syntax color
" ---------------------
syntax on							" 色付き
set t_Co=256						" 256色対応

try
	colorscheme hybrid				" カラースキーム設定
	set background=dark     " 正しいカラースキームのために
catch
	colorscheme default
endtry
"highlight LineNr ctermfg=darkgrey

" font
set guifont=Ricty\ Diminished:h11
set ambiwidth=double    " 2バイト半角対策


" font
try
    Guifont! Ricty Diminished:h11
catch
    Guifont! Consolas:h11
endtry
set ambiwidth=double    " 2バイト半角対策


" clipboard
set mouse=a
set clipboard&
set clipboard^=unnamedplus



