[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''

  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd

'''



[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested try | colorscheme hybrid | catch | endtry
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# sudo.vim
# usage:
# vim sudo:hoge		sudo権限でhogeを編集
# :w sudo:%			sudo権限でwrite
# :w sudo:piyo		sudo権限でpiyoに保存
# :e sudo:%			sudo権限で開き直す
[[plugins]]
repo = 'vim-scripts/sudo.vim'



# プロジェクトのrootディレクトリを探す子
[[plugins]]
repo = 'airblade/vim-rooter'

# tags自動更新
[[plugins]]
repo = 'szw/vim-tags'






[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

# JS libraries syntax
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'typescript']
hook_add = '''
let g:used_javascript_libs = 'jquery'
'''

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']
hook_add = '''
let g:js_indent_typescript = 1
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # cpp syntax
repo = 'vim-jp/cpp-vim'
on_ft = ['c', 'cpp']

[[plugins]] # nginx syntax
repo = 'evanmiller/nginx-vim-syntax'
on_ft = 'nginx'

[[plugins]] # tex syntax
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = 'ps1'

